#pragma once
enum class eAnchorMode
{
	TOP_LEFT, TOP_CENTER, TOP_RIGHT, MIDDLE_LEFT, MIDDLE_CENTER, MIDDLE_RIGHT, BOTTOM_LEFT, BOTTOM_CENTER, BOTTOM_RIGHT
};

enum class eComponentMessage
{
	UPDATE, RENDER
};